from src.controllers.controller import *
from src.controllers.erros import NotFoundController

routes ={
    #comum
    "index_route":"/","indexcontroller":IndexController.as_view("index"),
    "funcionario_route":"/adm","funcionario_controller":LoginFuncionario.as_view("loginfunc"),
    "not_found_route":404,"not_found_controller": NotFoundController.as_view("not_found"),
    "cadastro_route":"/cadastro_cliente","cadastro_cliente_controller":CadastroClienteController.as_view("cadastro"),
    "login_route":"/login_cliente","login_controller":LoginController.as_view("login"),
    "login_cliente_validacao_route":"/login_cliente_validacao","login_cliente_validacao_controller":LoginValicaoController.as_view("loginvalidacao"),
    "link_cadastro":"/link_cadastro/","link_cadastro_controller":LinkPaginaCadastroController.as_view("linkcadastro"),
    "cadastro_execucao":"/cadastro_execucao/","cadastro_execucao_controller":CadastroClienteController.as_view("cadastrocliente"),
    "gerar_extrato":"/gerar_extrato/<int:id>","gerar_extrato_controller":GerarExtratoController.as_view("gerarextrato"),
    "entrada_route":"/home","verifica_entrada_controller":VerificacaoEntrada.as_view("verificacaoentrada"),

    #cliente
    "area_cliente_route":"/area_cliente","area_cliente_controller":AreaClienteController.as_view("AreaCliente"),
    "update_route":"/update/cliente/<int:id>","update_controller":UpdateClienteController.as_view("update"),
    "home_user_id_route":"/home_user/<int:id>","home_user_id_controller":HomeUserIDController.as_view("homeuserid"),
    "home_user_route":"/home_user","home_user_controller":HomeUserController.as_view("homeuser"),
    "pagina_deposito_route":"/pagina_deposito/<int:id>","pagina_deposito_controller":paginaDepositoController.as_view("paginadeposito"),
    "realizar_deposito_route":"/realizar_deposito/<int:id>","realizar_deposito_controller":realizarDepositoController.as_view("realizardeposito"),
    "pagina_saque_route":"/pagina_saque/cliente/<int:id>","pagina_saque_controller":paginaSaqueController.as_view("paginasaque"),
    "realizar_saque_route":"/realizar_saque/cliente/<int:id>","realizar_saque_controller":realizarSaqueController.as_view("realizarsaque"),
    "link_extrato":"/link_extrato/<int:id>","link_extrato_controller":LinkExtratoController.as_view("linkextrato"),
    "dados_user_route":"/dados_user/cliente/<int:id>","dados_user_controller":DadosController.as_view("dadosuser"),
    "solicitacao_deletar":"/solicitacaodeletar/<int:id>","solicitacao_deletar_controller":DeleteClienteRequisicaoController.as_view("solicitacaodeletar"),
    "pagina_transferencia_route":"/pagina_transferencia/<int:id>","pagina_transferencia_controller":paginaTransferenciaController.as_view("transferencia"),
    "realizar_transferencia_route":"/realiazar_transferencia/<int:id>","realizar_tranferencia_controller":realizarTransferenciaController.as_view("realizartransferencia"),

    #gerete_de_agencia
    "index_admin_route":"/gerenteagencia","indexgacontroller":IndexController.as_view("indexga"),
    "home_gerente_agencia_id_route":"/home_gerente_agencia/<int:id>","home_gerente_agencia_id_controller":HomeGerenteAgenciaController.as_view("homegaid"),
    "home_gerente_conta":"/home_gerente_conta/<int:id>","home_gerente_conta_controller":HomeGerenteContaController.as_view("homegerenteconta"),
    "pagina_deposito_gerente_route":"/pagina_deposito_gerente/cliente/<int:id>","pagina_deposito_gerente_controller":paginaDepositoGerenteController.as_view("paginadepositogerente"),
    "realizar_deposito_gerente_route":"/realizar_gerente_deposito/cliente/<int:id>","realizar_deposito_gerente_controller":realizarDepositoGerenteController.as_view("realizardepositogerente"),
    "pagina_saque_gerente_route":"/pagina_gerente_saque/cliente/<int:id>","pagina_gerente_saque_controller":paginaSaqueGerenteController.as_view("paginasaquegerente"),
    "realizar_saque_gerente_route":"/realizar_saque_gerente/cliente/<int:id>","realizar_saque_gerente_controller":realizarSaqueGerenteController.as_view("realizarsaquegerente"),
    "link_modo_gerente_contas":"/link_modo_gerente_contas/<int:id>","modo_gerente_contas_controller":ModoGerenteAgenciaController.as_view("modogerente"),
    "link_gerenciar_contas":"/link_gerenciar_contas/<int:id>","link_gerenciar_contas_controller":LinkGerenciarContasController.as_view("linkgcontas"),
    "aprovar_contas":"/aprovar_contas/<int:id>","aprovar_contas_controller":AprovacaoContaController.as_view("aprovacaodeconta"),
    "link_aprovacao_deposito":"/link_aprovacao_deposito/<int:id>","link_aprovacao_deposito_controller":LinkAprovacaoDepositoController.as_view("linkaprovacaodeposito"),
    "aprovacao_deposito":"/aprovacao_deposito/<int:id>","aprovacao_deposito_controller":ExecucaoDepositoController.as_view("aprovacaodeposito"),
    "delete_route":"/delete/cliente/<int:id>","delete_controller":DeleteClienteController.as_view("delete"),
    "update_gerente_route":"/update/gerente/<int:id>","update_gerente_controller":UpdateGerenteController.as_view("updategerente"),
    "link_extrato_gerente":"/link_extrato_gerente/<int:id>","link_extrato_gerente_controller":LinkExtratoGerenteController.as_view("linkextratogerente"),
    "pagina_transferencia_gerente_route":"/pagina_transferencia_gerente/<int:id>","pagina_transferencia_gerente_controller":paginaTransferenciaGerenteController.as_view("transferenciagerente"),
    "realizar_transferencia_gerente_route":"/realiazar_transferencia_gerente/<int:id>","realizar_tranferencia_gerente_controller":realizarTransferenciaGerenteController.as_view("realizartransferenciagerente"),
    "link_vizualizar_conta_route":"/vizualizar_conta_gerente/<int:id>","vizualizar_conta_controller":VizualizarContaController.as_view("vizualizarconta"),
    "negarconta_route":"/negarconta_gerente/<int:id>","negarconta_controller":NegarContaController.as_view("negarconta"),
    "negardeposito_route":"/negardeposito_gerente/<int:id>","negardepositoconta_controller":NegarDepositoController.as_view("negardeposito"),

    #gerente_geral
    "home_gerente_geral_id_route":"/home_gerente_geral/<int:id>","home_gerente_geral_id_controller":HomeGerenteGeralController.as_view("homeggid"),
    "gerenciar_gerentes_link_route":"/gerenciar_gerentes","gerenciar_gerentes_controller":GerenciarGerentesLinkController.as_view("gerenciargerentes"),
    "gerenciar_banco_link_route":"/gerenciar_banco","gerenciar_banco_controller":GerenciarBancoLinkController.as_view("gerenciarbanco"),
    "gerenciar_agencias_link_route":"/gerenciar_agencias","gerenciar_agencias_controller":GerenciarAgenciaLinkController.as_view("gerenciaragencias"),
    "criar_agencia_route":"/criar_agencia","criar_agencia_controller":CadastrarAgenciaController.as_view("criaragencia"),
    "cadastro_GA_route":"/cadastro_GA","cadastro_GA_controller":CadastroGerenteAgencia.as_view("cadastroGA"),
    "banco_dados_route":"/banco_dados","banco_dados_controller":AlterarCapitalJurosController.as_view("bancodados"),
    "gerenciar_contas_gerente_geral_route":"/gerenciar_contas_GG","gerenciar_contas_gg_controller":LinkGerenciarContasGGController.as_view("gerenciarcontasGG"),
    "link_alterar_agencia_route":"/link_alterar_agencia/<int:id>","link_alterar_agencia_controller":LinkAlterarNomeAgenciaController.as_view("linkANAG"),
    "edicao_agencia_route":"/edicao_agencia/<int:id>","edicao_agencia_controller":AlterarNomeAgenciaController.as_view("EditarAgencia"),
    "detetar_agencia_route":"/deletar_agencia/<int:id>","deletar_agencia_controller":DeletarAgenciaController.as_view("DeletarAgencia"),
    "demitir_GA_route":"/demitir_GA/<int:id>","demitir_GA_controller":DemitirGerenteAgencia.as_view("demitirGA"),
    "link_aprovacao_deposito_GG_route":"/link_aprovacao_deposito_GG/","link_aprovacao_deposito_GG_controller":LinkAprovacaoDepositoGGController.as_view("LinkADGG"),
    "aprovacao_deposito_GG_route":"/provacao_deposito_GG/<int:id>","aprovacao_deposito_GG_controller":ExecucaoDepositoGGController.as_view("AprovacaoDGG"),
    "negar_conta_GG_route":"/negar_conta_GG/<int:id>","negar_conta_GG_controller":NegarContaGGController.as_view("NegarcontaGG"),
    "vizualirzar_conta_GG_route":"/vizualizar_conta_GG/<int:id>","vizualizar_conta_GG_controller":VizualizarContaGGController.as_view("VizualizarcontaGG"),
    "delete_gg_route":"/delete_gg/<int:id>","delete_gg_controller":DeleteClienteGGController.as_view("deleteGG"),
    "cadastro_gg_route":"/cadastro_gg","cadastro_gg_controller":CadastroGGInicioController.as_view("cadastroGG"),
}


